"""
Django settings for Dovetec Enterprises Web Project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import sys
import dotenv
# Load environment variables from .env file
dotenv.load_dotenv()
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Add the project directory to the Python path
sys.path.append(BASE_DIR)



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise ValueError('SECRET_KEY environment variable is not set')

# SECURITY WARNING: don't run with debug turned on in production!
# Set DEBUG to True for development, but respect environment variable if set
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 't')
if os.getenv('VERCEL_ENV') == 'production' and os.getenv('VERCEL_URL') == 'dovetecenterprises.netlify.app':

    DEBUG = False

# Get Vercel URL from environment variable or use wildcard
VERCEL_URL = os.getenv('VERCEL_URL', '')

ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', '').split(',') if h.strip()] or ['localhost', '127.0.0.1']
if VERCEL_URL:
    ALLOWED_HOSTS.append(VERCEL_URL)
    ALLOWED_HOSTS.append(f'.{VERCEL_URL}')
if os.getenv('VERCEL_ENV') == 'production' and os.getenv('VERCEL_URL') == 'dovetecenterprises.netlify.app':

    DEBUG = False
INSTALLED_APPS = [
    'whitenoise.runserver_nostatic',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dovetecenterprises',  # Main project app (for management commands)
    'app',  # 'app' app
    'home',  # 'home' app
    'rest_framework',  # Django REST framework
    'django_extensions',  # Django extensions
    'froala_editor',
    'shop',
    'adverts',
    'community',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Message settings
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

# Define message tags that match Bootstrap classes
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

ROOT_URLCONF = 'dovetecenterprises.urls'



# Define the template directory
TEMPLATE_DIR = os.path.join(BASE_DIR, 'templates')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'dovetecenterprises.context_processors.site_metadata',

            ],
        },
    },
]
WSGI_APPLICATION = 'dovetecenterprises.wsgi.application'



# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

import dj_database_url
import socket

# Get DATABASE_URL from .env
DATABASE_URL = os.getenv('DATABASE_URL')

# Default to SQLite
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Try to use PostgreSQL if DATABASE_URL is set
if DATABASE_URL:
    try:
        # Use dj-database-url for robustness
        DATABASES['default'] = dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    except Exception as e:
        if os.getenv('VERCEL'):
            # In Vercel, we want to know if DB configuration fails
            print(f"CRITICAL ERROR: Database configuration failed: {e}")
            raise
        print(f"Error configuring database: {e}. Falling back to SQLite for local development.")
else:
    if os.getenv('VERCEL'):
        print("WARNING: DATABASE_URL not found on Vercel. Falling back to local SQLite.")

# AUTHENTICATION SETTINGS
# ──────────────────────────────────────────────────────────────
LOGIN_URL = 'login_view'
LOGIN_REDIRECT_URL = 'dashboard_router'
LOGOUT_REDIRECT_URL = 'home'

# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
# AUTH USER MODEL
AUTH_USER_MODEL = 'home.User'

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# WhiteNoise configuration
WHITENOISE_USE_FINDERS = True

# Ensure the static directory exists (not on Vercel as it is read-only)
if not os.getenv('VERCEL'):
    os.makedirs(STATIC_ROOT, exist_ok=True)
    for static_dir in STATICFILES_DIRS:
        os.makedirs(static_dir, exist_ok=True)

# Media files (Images, Videos, etc)
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Durable media: prefer Vercel Blob when BLOB_READ_WRITE_TOKEN is set (local
# FileSystemStorage is read-only under /var/task on Vercel serverless).
BLOB_READ_WRITE_TOKEN = (os.getenv('BLOB_READ_WRITE_TOKEN') or '').strip()
BLOB_ACCESS = (os.getenv('BLOB_ACCESS') or 'public').strip().lower()
BLOB_STORE_ID = (os.getenv('BLOB_STORE_ID') or '').strip()
BLOB_PUBLIC_URL = (os.getenv('BLOB_PUBLIC_URL') or '').strip()

STORAGES = {
    'default': {
        'BACKEND': (
            'dovetecenterprises.blob_storage.VercelBlobStorage'

            if BLOB_READ_WRITE_TOKEN
            else ('django.core.files.storage.FileSystemStorage' if os.getenv('VERCEL') != '1' else 'dovetecenterprises.blob_storage.NoOpStorage')

        ),
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

# Local-media upload policy. This is intentionally explicit so all future
# upload entry points (CRM, careers, products, and portfolio) share limits.
MEDIA_MAX_UPLOAD_BYTES = 15 * 1024 * 1024  # 15 MiB
# Vercel Functions reject request bodies over ~4.5 MB; keep server uploads under it.
if os.getenv('VERCEL'):
    MEDIA_MAX_UPLOAD_BYTES = min(MEDIA_MAX_UPLOAD_BYTES, 4 * 1024 * 1024)
MEDIA_ALLOWED_CONTENT_TYPES = {
    'image/jpeg', 'image/png', 'image/webp', 'image/gif',
    'application/pdf', 'text/plain', 'application/zip',
    'application/x-zip-compressed', 'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-powerpoint',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'application/dxf',
}

# CKEditor Settings
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': 300,
    },
}

CKEDITOR_STATIC_URL = 'ckeditor/'
CKEDITOR_UPLOAD_PATH = 'content/ckeditor/'
CKEDITOR_IMAGE_BACKEND = 'pillow'



# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Email settings
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes', 'on')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '').replace(' ', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'webmaster@localhost')

# Contact settings
CONTACT_EMAIL = os.getenv('CONTACT_EMAIL', 'contact@dovetecenterprises.tech')

FEEDBACK_EMAIL = os.getenv('FEEDBACK_EMAIL', CONTACT_EMAIL)
REPORT_EMAIL = os.getenv('REPORT_EMAIL', CONTACT_EMAIL)

# WhatsApp Business API (Meta Cloud API)
WHATSAPP_ACCESS_TOKEN = os.getenv('WHATSAPP_ACCESS_TOKEN', '')
WHATSAPP_PHONE_NUMBER_ID = os.getenv('WHATSAPP_PHONE_NUMBER_ID', '')
WHATSAPP_BUSINESS_ACCOUNT_ID = os.getenv('WHATSAPP_BUSINESS_ACCOUNT_ID', '')
WHATSAPP_VERIFIED_NUMBER = os.getenv('WHATSAPP_VERIFIED_NUMBER', '+254742253400')
WHATSAPP_WEBHOOK_VERIFY_TOKEN = os.getenv('WHATSAPP_WEBHOOK_VERIFY_TOKEN', 'vercel-whatsapp-verify')
WHATSAPP_NOTIFY_STAFF = os.getenv('WHATSAPP_NOTIFY_STAFF', 'True').lower() in ('true', '1', 'yes', 'on')
WHATSAPP_NOTIFY_CLIENT = os.getenv('WHATSAPP_NOTIFY_CLIENT', 'True').lower() in ('true', '1', 'yes', 'on')

# Ticket queue — default staff assignee email for new public intake tickets.
TICKET_DEFAULT_ASSIGNEE = os.getenv('TICKET_DEFAULT_ASSIGNEE', '')
# Notify staff by email on ticket assign/transfer/refer (in-app always on).
TICKET_NOTIFY_EMAIL = os.getenv('TICKET_NOTIFY_EMAIL', 'True').lower() in ('true', '1', 'yes', 'on')

# M-Pesa Daraja Settings
MPESA_CONSUMER_KEY = os.getenv('MPESA_CONSUMER_KEY', '')
MPESA_CONSUMER_SECRET = os.getenv('MPESA_CONSUMER_SECRET', '')
MPESA_SHORTCODE = os.getenv('MPESA_SHORTCODE', '')
MPESA_PASSKEY = os.getenv('MPESA_PASSKEY', '')
MPESA_PHONE_NUMBER = os.getenv('MPESA_PHONE_NUMBER', '')
MPESA_CALLBACK_URL = os.getenv('MPESA_CALLBACK_URL', '')

# PayPal Settings
PAYPAL_CLIENT_ID = os.getenv('PAYPAL_CLIENT_ID', '')
PAYPAL_SECRET = os.getenv('PAYPAL_SECRET', '')
PAYPAL_SUCCESS_URL = os.getenv('PAYPAL_SUCCESS_URL', '')
PAYPAL_CANCEL_URL = os.getenv('PAYPAL_CANCEL_URL', '')

# Froala WYSIWYG — set FROALA_KEY in .env / Vercel to silence the unlicensed banner.
# Free trial: https://froala.com/get-trial-key/  ·  Paid: https://froala.com/wysiwyg-editor/pricing/
FROALA_EDITOR_OPTIONS = {}
_froala_key = (os.getenv('FROALA_KEY') or os.getenv('FROALA_LICENSE_KEY') or '').strip()
if _froala_key:
    FROALA_EDITOR_OPTIONS['key'] = _froala_key

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'stderr': {
            'class': 'logging.StreamHandler',
            'stream': 'ext://sys.stderr',
        },
    },
    'loggers': {
        'app.crm': {
            'handlers': ['stderr'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}
