# Generated by Django 6.1.1 on 2026-09-20 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_serviceinquiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceinquiry',
            options={'ordering': ['-stage_updated_at']},
        ),
        migrations.AddField(
            model_name='serviceinquiry',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Sales rep handling this lead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceinquiry',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceinquiry',
            name='estimated_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Estimated deal value (KES).', max_digits=12),
        ),
        migrations.AddField(
            model_name='serviceinquiry',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal follow-up notes.', null=True),
        ),
        migrations.AddField(
            model_name='serviceinquiry',
            name='stage',
            field=models.CharField(choices=[('new', 'New Lead'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('won', 'Won (Converted)'), ('lost', 'Lost')], db_index=True, default='new', help_text='Current stage in the sales funnel.', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceinquiry',
            name='stage_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='serviceinquiry',
            index=models.Index(fields=['stage', '-stage_updated_at'], name='app_service_stage_7d8710_idx'),
        ),
    ]
