# Generated by Django 6.1.1 on 2026-09-21 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_crm_organizations_contacts_and_enriched_inquiries'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mediaasset',
            new_name='app_mediaas_content_4cd07a_idx',
            old_name='app_mediaas_content_3eaa95_idx',
        ),
        migrations.RenameIndex(
            model_name='mediaasset',
            new_name='app_mediaas_owner_i_12a8bd_idx',
            old_name='app_mediaas_owner_i_1f9c6f_idx',
        ),
    ]
