# Generated by Django 6.1.1 on 2026-09-21 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_app_mediaas_content_3eaa95_idx_app_mediaas_content_4cd07a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='large_image',
            field=models.ImageField(blank=True, null=True, upload_to='derivatives/large/'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='medium_image',
            field=models.ImageField(blank=True, null=True, upload_to='derivatives/medium/'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='small_image',
            field=models.ImageField(blank=True, null=True, upload_to='derivatives/small/'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('service', models.CharField(blank=True, choices=[('software', 'Software Engineering'), ('it', 'IT Solutions'), ('consulting', 'Consulting Services'), ('other', 'Other')], max_length=20)),
                ('source', models.CharField(blank=True, choices=[('website', 'Website contact form'), ('service_page', 'Service request form'), ('referral', 'Referral'), ('manual', 'Manual entry')], max_length=30)),
                ('stage', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated project budget (KES).', max_digits=12, null=True)),
                ('actual_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Actual project spend.', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('deliverables', models.TextField(blank=True, help_text='Comma-separated list of deliverables', null=True)),
                ('client_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachments', models.ManyToManyField(blank=True, related_name='projects', related_query_name='project', to='app.mediaasset')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='app.contact')),
                ('converted_from_inquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_projects', to='app.serviceinquiry')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='app.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stage', 'priority'], name='app_project_stage_29020f_idx'), models.Index(fields=['organization', 'status'], name='app_project_organiz_ec18a0_idx')],
            },
        ),
    ]
