# Generated by Django 6.1.1 on 2026-09-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_case_study'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='casestudy',
            new_name='app_casestu_status_1ae189_idx',
            old_name='idx_cs_status_featured',
        ),
        migrations.RenameIndex(
            model_name='casestudy',
            new_name='app_casestu_categor_720371_idx',
            old_name='idx_cs_category',
        ),
        migrations.RenameIndex(
            model_name='casestudy',
            new_name='app_casestu_publish_0556c7_idx',
            old_name='idx_cs_published',
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='business_challenge',
            field=models.TextField(blank=True, help_text='Business challenge section content'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='competitor_data',
            field=models.TextField(blank=True, help_text='Competitor analysis data (JSON or HTML)'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='features',
            field=models.TextField(blank=True, help_text='Features & functionalities section content'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='major_screens',
            field=models.TextField(blank=True, help_text='Major screens section content'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='matrix_data',
            field=models.TextField(blank=True, help_text='Eisenhower matrix data'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='objectives',
            field=models.TextField(blank=True, help_text='Objectives & goals section content'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='persona_data',
            field=models.TextField(blank=True, help_text='User persona data (JSON or HTML)'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='problem_statement',
            field=models.TextField(blank=True, help_text='Problem statement section content'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='research_findings',
            field=models.TextField(blank=True, help_text='Quantitative research findings'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='root_cause',
            field=models.TextField(blank=True, help_text='Root cause analysis content'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='screens',
            field=models.TextField(blank=True, help_text='Screens section content'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='sketches',
            field=models.TextField(blank=True, help_text='Sketches section content'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='task_flows',
            field=models.TextField(blank=True, help_text='Task flows content'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='task_mapping',
            field=models.TextField(blank=True, help_text='Task mapping section content'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='unique_features',
            field=models.TextField(blank=True, help_text='Unique features section content'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='user_challenges',
            field=models.TextField(blank=True, help_text='Product user challenges section content'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='user_needs',
            field=models.TextField(blank=True, help_text='User needs section content'),
        ),
    ]
