# Generated by Django 6.1 on 2026-09-23 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_idx_cs_status_featured_app_casestu_status_1ae189_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('intro', models.TextField(blank=True, help_text='Shown to the client before the questions.', null=True)),
                ('context', models.CharField(choices=[('discovery', 'Discovery'), ('onboarding', 'Onboarding'), ('end_of_service', 'End of Service'), ('satisfaction', 'Satisfaction'), ('custom', 'Custom')], db_index=True, default='custom', max_length=40)),
                ('industry', models.CharField(blank=True, help_text='Optional industry filter; blank matches any industry.', max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['context', 'title'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='context',
            field=models.CharField(blank=True, help_text='Optional context tag (discovery, satisfaction, …) for import filters.', max_length=40),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='context',
            field=models.CharField(blank=True, help_text='Lifecycle context that produced this questionnaire, if any.', max_length=40),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(blank=True, help_text='Live questionnaire this question belongs to (clone target).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.questionnaire'),
        ),
        migrations.AddField(
            model_name='question',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Reusable library template this question belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.questionnairetemplate'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='source_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spawned_questionnaires', to='app.questionnairetemplate'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('issue', 'Issue / Support'), ('enquiry', 'Sales Enquiry')], db_index=True, default='issue', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('waiting', 'Waiting on Client'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='new', max_length=20)),
                ('service', models.CharField(choices=[('software', 'Software Engineering'), ('it', 'IT Solutions'), ('consulting', 'Consulting Services'), ('other', 'Other')], default='other', max_length=20)),
                ('source', models.CharField(choices=[('website', 'Website contact form'), ('service_page', 'Service request form'), ('referral', 'Referral'), ('manual', 'Manual entry')], default='website', max_length=30)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('budget_range', models.CharField(choices=[('unspecified', 'Not specified'), ('under_50k', 'Under KES 50,000'), ('50k_250k', 'KES 50,000–250,000'), ('250k_1m', 'KES 250,000–1,000,000'), ('over_1m', 'Over KES 1,000,000')], default='unspecified', max_length=30)),
                ('timeline', models.CharField(blank=True, max_length=120)),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp')], default='email', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Staff member who owns this ticket.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='app.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(blank=True, help_text='Sales funnel lead after escalation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='app.serviceinquiry')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='app.organization')),
                ('referred_to', models.ForeignKey(blank=True, help_text='Staff member referred for advice (ownership unchanged).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('transferred', 'Transferred'), ('referred', 'Referred'), ('status_change', 'Status Changed'), ('priority_change', 'Priority Changed'), ('escalated', 'Escalated'), ('note', 'Note'), ('converted', 'Converted to Lead'), ('questionnaire', 'Questionnaire')], default='note', max_length=30)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_activities_from', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='app.ticket')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_activities_to', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'priority'], name='app_ticket_status_1b6e59_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_to', 'status'], name='app_ticket_assigne_22916b_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketactivity',
            index=models.Index(fields=['ticket', 'action'], name='app_ticketa_ticket__c29fd5_idx'),
        ),
    ]
