# Generated by Django 6.1 on 2026-09-24 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_seed_samples'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurerequest',
            name='slug',
            field=models.SlugField(max_length=220, unique=True),
        ),
        migrations.CreateModel(
            name='QuestionnaireEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('sent', 'Sent to client'), ('answered', 'Answered'), ('updated', 'Answer updated'), ('completed', 'Completed'), ('reopened', 'Reopened'), ('clear_responses', 'Responses cleared'), ('question_added', 'Question added'), ('questions_imported', 'Questions imported'), ('staff_edited', 'Staff correction'), ('staff_deleted', 'Staff deleted answer')], db_index=True, max_length=30)),
                ('content', models.TextField(blank=True)),
                ('answer_snapshot', models.TextField(blank=True, help_text='Answer value at the time of this event (for response history).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Who performed the action; null = system or unauthenticated client email match.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaire_events', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='app.question')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app.questionnaire')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['questionnaire', 'created_at'], name='app_questio_questio_a7f472_idx')],
            },
        ),
    ]
