# Generated by Django 6.1.1 on 2026-09-25 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_featurerequest_slug_questionnaireevent'),
        ('home', '0018_notification_whatsapp_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('recipient_WhatsApp', models.CharField(blank=True, max_length=20)),
                ('channel', models.CharField(choices=[('notify', 'General notification'), ('inquiry', 'New inquiry'), ('project', 'Project update'), ('questionnaire', 'Questionnaire event'), ('ticket', 'Ticket update')], default='notify', max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('delivered', 'Delivered'), ('read', 'Read')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_notifications', to='home.notification')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='app_whatsap_status_669bcf_idx')],
            },
        ),
    ]
