# Generated by Django 6.1.1 on 2026-09-21 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_remove_community_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='flag_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='flagged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_flagged', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_moderated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='moderation_state',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('hidden', 'Hidden'), ('removed', 'Removed'), ('flagged', 'Flagged')], db_index=True, default='pending', help_text='Moderation status. Posts require approval before public visibility.', max_length=20),
        ),
        migrations.AddField(
            model_name='comment',
            name='moderator_decision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='flag_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='flagged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_flagged', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_moderated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='moderation_state',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('hidden', 'Hidden'), ('removed', 'Removed'), ('flagged', 'Flagged')], db_index=True, default='pending', help_text='Moderation status. Posts require approval before public visibility.', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='moderator_decision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='flag_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='flagged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_flagged', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_moderated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='moderation_state',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('hidden', 'Hidden'), ('removed', 'Removed'), ('flagged', 'Flagged')], db_index=True, default='pending', help_text='Moderation status. Posts require approval before public visibility.', max_length=20),
        ),
        migrations.AddField(
            model_name='reply',
            name='moderator_decision',
            field=models.TextField(blank=True, null=True),
        ),
    ]
