# Generated by Django 6.1 on 2026-09-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_category_canonical_url_category_meta_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Override meta title for SEO', max_length=200)),
                ('meta_description', models.CharField(blank=True, help_text='Override meta description for SEO', max_length=500)),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL for SEO', max_length=500)),
                ('og_title', models.CharField(blank=True, help_text='Open Graph title', max_length=200)),
                ('og_description', models.CharField(blank=True, help_text='Open Graph description', max_length=500)),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image', null=True, upload_to='og_images/')),
                ('twitter_card', models.CharField(blank=True, help_text='Twitter card type (summary, summary_large_image)', max_length=50)),
                ('twitter_title', models.CharField(blank=True, help_text='Twitter title', max_length=200)),
                ('twitter_description', models.CharField(blank=True, help_text='Twitter description', max_length=500)),
                ('twitter_image', models.ImageField(blank=True, help_text='Twitter image', null=True, upload_to='twitter_images/')),
                ('published_at', models.DateTimeField(blank=True, help_text='Actual publication date', null=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('webinar', 'Webinar'), ('workshop', 'Workshop'), ('meetup', 'Meetup'), ('conference', 'Conference')], default='meetup', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_online', models.BooleanField(default=False)),
                ('registration_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['starts_at'],
                'indexes': [models.Index(fields=['is_published', 'starts_at'], name='community_e_is_publ_3a7715_idx')],
            },
        ),
    ]
