# Generated by Django 5.1.5 on 2026-04-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_newslettersubscription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='manual_recipients',
            field=models.TextField(blank=True, help_text='Ad-hoc email addresses separated by commas (e.g., contact@example.com, lead@example.com)'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='recipients',
            field=models.ManyToManyField(blank=True, limit_choices_to={'unsubscribed_at': None}, related_name='newsletters', to='home.newslettersubscription'),
        ),
    ]
