# Generated by Django 5.1.5 on 2026-04-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_newsletter_manual_recipients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='Future date to schedule publication', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
