# Generated by Django 5.1.5 on 2026-04-03 21:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_article_published_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscription',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
