# Generated by Django 5.1.5 on 2026-04-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_newslettersubscription_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscription',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
