# Generated by Django 5.1.5 on 2026-04-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_newslettersubscription_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='hashed_id',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='hashed_id',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
