# Generated by Django 6.1.1 on 2026-09-21 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_user_dashboard_permission_and_role_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('headcount', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='article',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL for SEO', max_length=500),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Override meta description for SEO', max_length=500),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Override meta title for SEO', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='og_description',
            field=models.CharField(blank=True, help_text='Open Graph description', max_length=500),
        ),
        migrations.AddField(
            model_name='article',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph image', null=True, upload_to='og_images/'),
        ),
        migrations.AddField(
            model_name='article',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Actual publication date', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='twitter_card',
            field=models.CharField(blank=True, help_text='Twitter card type (summary, summary_large_image)', max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='twitter_description',
            field=models.CharField(blank=True, help_text='Twitter description', max_length=500),
        ),
        migrations.AddField(
            model_name='article',
            name='twitter_image',
            field=models.ImageField(blank=True, help_text='Twitter image', null=True, upload_to='twitter_images/'),
        ),
        migrations.AddField(
            model_name='article',
            name='twitter_title',
            field=models.CharField(blank=True, help_text='Twitter title', max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='employment_type',
            field=models.CharField(blank=True, help_text='e.g., Full-time, Part-time, Contract, Internship', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='home.department'),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=200)),
                ('candidate_email', models.EmailField(max_length=254)),
                ('candidate_phone', models.CharField(blank=True, max_length=30)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, help_text='CV or resume file (max 5MB)', null=True, upload_to='job_applications/resumes/')),
                ('portfolio', models.FileField(blank=True, help_text='Portfolio or work samples', null=True, upload_to='job_applications/portfolios/')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('hired', 'Hired')], db_index=True, default='new', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Internal recruiter notes', null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_applications_assigned', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='home.job')),
            ],
            options={
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['status', 'applied_at'], name='home_jobapp_status_7bb4e9_idx'), models.Index(fields=['job', 'status'], name='home_jobapp_job_id_9e30de_idx')],
            },
        ),
    ]
