# Generated by Django 6.1.1 on 2026-09-21 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_department_remove_user_role_article_canonical_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Application Created'), ('status_change', 'Status Changed'), ('assigned', 'Assigned to Recruiter'), ('interview', 'Interview Scheduled'), ('offer', 'Offer Extended'), ('rejected', 'Rejected'), ('note', 'Note Added'), ('attachment', 'Attachment Uploaded')], default='note', max_length=30)),
                ('content', models.TextField()),
                ('attachments', models.TextField(blank=True, help_text='Comma-separated file references', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('phone', 'Phone Screening'), ('video', 'Video Call'), ('in_person', 'In-Person'), ('on_site', 'On-Site')], default='video', max_length=20)),
                ('interview_stage', models.CharField(choices=[('initial', 'Initial Screening'), ('technical', 'Technical'), ('behavioral', 'Behavioral'), ('final', 'Final'), ('hr', 'HR')], default='initial', max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('location', models.CharField(blank=True, help_text='Location or video link', max_length=500)),
                ('notes', models.TextField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('pass', 'Passed'), ('fail', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=100)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('source_type', models.CharField(choices=[('job_board', 'Job Board'), ('social_media', 'Social Media'), ('referral', 'Referral Program'), ('career_fair', 'Career Fair'), ('company_website', 'Company Website'), ('internal', 'Internal'), ('other', 'Other')], default='job_board', max_length=30)),
                ('cost_per_hire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('applications_count', models.PositiveIntegerField(default=0)),
                ('hired_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-hired_count'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='candidate_linkedin',
            field=models.URLField(blank=True, help_text="Candidate's LinkedIn profile URL", max_length=500),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department the applicant is applying to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='home.department'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='employee_type',
            field=models.CharField(blank=True, help_text='Full-time, Part-time, Contract, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interview_date',
            field=models.DateTimeField(blank=True, help_text='Scheduled interview date and time.', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interview_location',
            field=models.CharField(blank=True, help_text='Interview location or video link.', max_length=500),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='offer_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Offered salary.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='offer_conditions',
            field=models.TextField(blank=True, help_text='Offer terms and conditions.', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='offer_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Application priority for recruiter workflow.', max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='rating',
            field=models.PositiveIntegerField(blank=True, help_text='Candidate rating (1-5) by recruiter.', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection.', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ats_applications_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='source',
            field=models.CharField(choices=[('job_portal', 'Job Portal'), ('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('referral', 'Employee Referral'), ('company_website', 'Company Website'), ('social_media', 'Social Media'), ('career_fair', 'Career Fair'), ('internal', 'Internal Transfer')], default='job_portal', help_text='How the candidate found this job posting.', max_length=30),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='source_detail',
            field=models.CharField(blank=True, help_text='Specific source detail (e.g., job board name, referrer name)', max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text="Candidate's availability start date.", null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='status_changed_at',
            field=models.DateTimeField(auto_now=True, help_text='When current status was set.'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Recruiter assigned to this application.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ats_applications_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='candidate_email',
            field=models.EmailField(help_text='Primary email for candidate communication.', max_length=254),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='candidate_name',
            field=models.CharField(help_text='Full legal name of the candidate.', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(blank=True, help_text="Candidate's cover letter", null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(help_text='The job position being applied for.', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='home.job'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal recruiter notes.', null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='portfolio',
            field=models.FileField(blank=True, help_text='Portfolio or work samples link/file', null=True, upload_to='job_applications/portfolios/'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, help_text='CV or resume file (PDF, DOC, DOCX - max 5MB)', null=True, upload_to='job_applications/resumes/'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('new', 'New Application'), ('screened', 'Screened'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('interview_complete', 'Interview Complete'), ('assessment', 'Assessment'), ('offer', 'Offer Extended'), ('negotiation', 'In Negotiation'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='new', help_text='Current stage in the applicant tracking pipeline.', max_length=30),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['department', 'status'], name='home_jobapp_departm_19500d_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['candidate_email'], name='home_jobapp_candida_ff6094_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['source', 'applied_at'], name='home_jobapp_source_06b709_idx'),
        ),
        migrations.AddField(
            model_name='applicationnote',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='home.jobapplication'),
        ),
        migrations.AddField(
            model_name='applicationnote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interview',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='home.jobapplication'),
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews_conducted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='applicationnote',
            index=models.Index(fields=['application', 'action'], name='home_applic_applica_d99d65_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationnote',
            index=models.Index(fields=['created_at'], name='home_applic_created_1a29c5_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['scheduled_at', 'interviewer'], name='home_interv_schedul_16eb6a_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['application', 'interview_stage'], name='home_interv_applica_c46380_idx'),
        ),
    ]
