# Generated by Django 6.1 on 2026-09-23 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_department_canonical_url_department_meta_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('assigned', 'Assigned'), ('transferred', 'Transferred'), ('referred', 'Referred'), ('status_change', 'Status changed'), ('priority_change', 'Priority changed'), ('escalated', 'Escalated'), ('converted', 'Converted'), ('stage_change', 'Stage changed'), ('questionnaire_sent', 'Questionnaire sent'), ('questionnaire_completed', 'Questionnaire completed'), ('note', 'Note')], default='note', max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('email_sent', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_actor', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='home_notifi_recipie_98b92e_idx')],
            },
        ),
    ]
