# Generated by Django 6.1.1 on 2026-09-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='whatsapp_sent',
            field=models.BooleanField(default=False),
        ),
    ]
