# Generated by Django 6.1 on 2026-09-26 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_notification_whatsapp_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_discussion',
            field=models.BooleanField(default=False, help_text='Mark as a community discussion point'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_resource',
            field=models.BooleanField(default=False, help_text='Mark as a downloadable resource'),
        ),
        migrations.AddField(
            model_name='article',
            name='resource_file',
            field=models.FileField(blank=True, help_text='Downloadable resource file', null=True, upload_to='resources'),
        ),
        migrations.AddField(
            model_name='article',
            name='resource_type',
            field=models.CharField(blank=True, choices=[('document', 'Document (PDF/Doc)'), ('guide', 'Guide/Tutorial'), ('template', 'Template'), ('reference', 'Reference Material'), ('tool', 'Tool/Software'), ('video', 'Video'), ('other', 'Other')], default='other', help_text='Type of resource', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='resource_url',
            field=models.URLField(blank=True, help_text='External resource URL', max_length=500),
        ),
        migrations.CreateModel(
            name='DiscussionTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('active', 'Active'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('reply_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_topics', to='home.profile')),
            ],
            options={
                'ordering': ['-is_pinned', '-vote_count', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='discussion_topic',
            field=models.ForeignKey(blank=True, help_text='Associated discussion topic', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='home.discussiontopic'),
        ),
    ]
