# Generated by Django 6.1.1 on 2026-09-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_article_resource_discussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='accent_color',
            field=models.CharField(default='#007bff', help_text='Brand accent color for email design', max_length=7),
        ),
    ]
