# Generated by Django 6.1.1 on 2026-09-27 19:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_newsletterattachment_newsletterlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='advertisement',
            field=models.ForeignKey(blank=True, help_text='Related advertisement if this newsletter is an ad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletters', to='home.advertisement'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='allow_attachments',
            field=models.BooleanField(default=True, help_text='Allow attachments in this newsletter'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='click_tracking_enabled',
            field=models.BooleanField(default=True, help_text='Enable click tracking'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='content_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the related content', null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='content_type',
            field=models.CharField(blank=True, help_text='Content type: article, service, product, case_study, resource, advertisement', max_length=20),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='resend_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this newsletter has been resent'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='tracking_pixel_enabled',
            field=models.BooleanField(default=True, help_text='Enable tracking pixel for open tracking'),
        ),
        migrations.AddField(
            model_name='newsletterlog',
            name='tracking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Tracking identifier for open/click tracking', unique=True),
        ),
        migrations.AddIndex(
            model_name='newsletter',
            index=models.Index(fields=['content_type', 'content_id'], name='home_newsle_content_b0da99_idx'),
        ),
    ]
