# Generated by Django 6.1.1 on 2026-09-28 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('home', '0022_newsletter_advertisement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='adverts',
            field=models.ManyToManyField(blank=True, help_text='Advertisements to render as blocks in this newsletter', related_name='newsletter_placements', to='home.advertisement'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='cta_label',
            field=models.CharField(blank=True, help_text='Call-to-action button label', max_length=100),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='cta_text',
            field=models.TextField(blank=True, help_text='Call-to-action body copy'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='cta_title',
            field=models.CharField(blank=True, help_text='Call-to-action headline', max_length=200),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='cta_url',
            field=models.URLField(blank=True, help_text='Call-to-action destination URL', max_length=500),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='preheader',
            field=models.CharField(blank=True, help_text='Preview text shown in the inbox next to the subject', max_length=300),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Optional subtitle shown under the headline', max_length=300),
        ),
        migrations.AddField(
            model_name='newsletterlog',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='advertisement',
            field=models.ForeignKey(blank=True, help_text='Primary advertisement for this newsletter', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletters', to='home.advertisement'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('partial', 'Partially Sent'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='newsletterlog',
            name='opened',
            field=models.BooleanField(default=False, help_text='Tracking pixel fired'),
        ),
        migrations.AlterField(
            model_name='newsletterlog',
            name='read',
            field=models.BooleanField(default=False, help_text='Recipient signed in from this email'),
        ),
        migrations.AlterField(
            model_name='newsletterlog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('read', 'Read'), ('bounced', 'Bounced'), ('failed', 'Failed'), ('unsubscribed', 'Unsubscribed')], default='sent', max_length=20),
        ),
        migrations.CreateModel(
            name='NewsletterContentReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('article', 'Article'), ('resource', 'Resource'), ('service', 'Service'), ('product', 'Product'), ('case_study', 'Case Study'), ('advertisement', 'Advertisement')], default='article', max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_references', to='home.newsletter')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['newsletter', 'kind'], name='home_newsle_newslet_684148_idx')],
            },
        ),
    ]
