# Generated by Django 6.1.1 on 2026-09-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_newsletter_adverts_newsletter_cta_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='newsletter_click_count',
            field=models.PositiveIntegerField(default=0, help_text='Newsletter link clicks attributed to this article'),
        ),
        migrations.AddField(
            model_name='article',
            name='newsletter_failed_count',
            field=models.PositiveIntegerField(default=0, help_text='Newsletter deliveries that failed'),
        ),
        migrations.AddField(
            model_name='article',
            name='newsletter_open_count',
            field=models.PositiveIntegerField(default=0, help_text='Newsletter opens attributed to this article'),
        ),
        migrations.AddField(
            model_name='article',
            name='newsletter_read_count',
            field=models.PositiveIntegerField(default=0, help_text='Newsletter recipients who signed in'),
        ),
        migrations.AddField(
            model_name='article',
            name='newsletter_sent_count',
            field=models.PositiveIntegerField(default=0, help_text='Times included in a newsletter send'),
        ),
    ]
